# MIT License
#
# Copyright (c) 2023-2024 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# This file has been autogenerated, do not modify.


"""
(No short description)


"""

import cython
import ctypes
import enum

from rocm.llvm.c.lljit import LLVMOrcLLJITBuilderRef
from rocm.llvm.c.lljit import LLVMOrcLLJITRef
from rocm.llvm.c.lljit import LLVMOrcCreateLLJITBuilder
from rocm.llvm.c.lljit import LLVMOrcDisposeLLJITBuilder
from rocm.llvm.c.lljit import LLVMOrcLLJITBuilderSetJITTargetMachineBuilder
from rocm.llvm.c.lljit import LLVMOrcLLJITBuilderSetObjectLinkingLayerCreator
from rocm.llvm.c.lljit import LLVMOrcCreateLLJIT
from rocm.llvm.c.lljit import LLVMOrcDisposeLLJIT
from rocm.llvm.c.lljit import LLVMOrcLLJITGetExecutionSession
from rocm.llvm.c.lljit import LLVMOrcLLJITGetMainJITDylib
from rocm.llvm.c.lljit import LLVMOrcLLJITGetTripleString
from rocm.llvm.c.lljit import LLVMOrcLLJITGetGlobalPrefix
from rocm.llvm.c.lljit import LLVMOrcLLJITMangleAndIntern
from rocm.llvm.c.lljit import LLVMOrcLLJITAddObjectFile
from rocm.llvm.c.lljit import LLVMOrcLLJITAddObjectFileWithRT
from rocm.llvm.c.lljit import LLVMOrcLLJITAddLLVMIRModule
from rocm.llvm.c.lljit import LLVMOrcLLJITAddLLVMIRModuleWithRT
from rocm.llvm.c.lljit import LLVMOrcLLJITLookup
from rocm.llvm.c.lljit import LLVMOrcLLJITGetObjLinkingLayer
from rocm.llvm.c.lljit import LLVMOrcLLJITGetObjTransformLayer
from rocm.llvm.c.lljit import LLVMOrcLLJITGetIRTransformLayer
from rocm.llvm.c.lljit import LLVMOrcLLJITGetDataLayoutStr


from rocm.llvm.c.types import LLVMMemoryBufferRef
from rocm.llvm.c.types import LLVMContextRef
from rocm.llvm.c.types import LLVMModuleRef
from rocm.llvm.c.types import LLVMTypeRef
from rocm.llvm.c.types import LLVMValueRef
from rocm.llvm.c.types import LLVMBasicBlockRef
from rocm.llvm.c.types import LLVMMetadataRef
from rocm.llvm.c.types import LLVMNamedMDNodeRef
from rocm.llvm.c.types import LLVMValueMetadataEntry
from rocm.llvm.c.types import LLVMBuilderRef
from rocm.llvm.c.types import LLVMDIBuilderRef
from rocm.llvm.c.types import LLVMModuleProviderRef
from rocm.llvm.c.types import LLVMPassManagerRef
from rocm.llvm.c.types import LLVMUseRef
from rocm.llvm.c.types import LLVMOperandBundleRef
from rocm.llvm.c.types import LLVMAttributeRef
from rocm.llvm.c.types import LLVMDiagnosticInfoRef
from rocm.llvm.c.types import LLVMComdatRef
from rocm.llvm.c.types import LLVMModuleFlagEntry
from rocm.llvm.c.types import LLVMJITEventListenerRef
from rocm.llvm.c.types import LLVMBinaryRef


from rocm.llvm.c.error import LLVMErrorRef
from rocm.llvm.c.error import LLVMGetErrorTypeId
from rocm.llvm.c.error import LLVMConsumeError
from rocm.llvm.c.error import LLVMGetErrorMessage
from rocm.llvm.c.error import LLVMDisposeErrorMessage
from rocm.llvm.c.error import LLVMGetStringErrorTypeId
from rocm.llvm.c.error import LLVMCreateStringError

@cython.embedsignature(True)
def LLVMOrcLLJITEnableDebugSupport(object J):
    r"""(No short description, might be part of a group.)

    Install the plugin that submits debug objects to the executor. Executors must
    expose the llvm_orc_registerJITLoaderGDBWrapper symbol.

    Args:
        J (`~.LLVMOrcOpaqueLLJIT`/`~.object`):
            (undocumented)
    """
    _LLVMOrcLLJITEnableDebugSupport__retval = LLVMOpaqueError.fromPtr(clljitutils.LLVMOrcLLJITEnableDebugSupport(
        LLVMOrcOpaqueLLJIT.fromPyobj(J).getElementPtr()))
    return None if _LLVMOrcLLJITEnableDebugSupport__retval._ptr == NULL else _LLVMOrcLLJITEnableDebugSupport__retval

__all__ = [
    "LLVMOrcLLJITEnableDebugSupport",
]