# MIT License
# 
# Copyright (c) 2023 Advanced Micro Devices, Inc.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# This file has been autogenerated, do not modify.


"""
(No short description)

Attributes:
    LLVMTargetDataRef:
        alias of `~.LLVMOpaqueTargetData`

    LLVMTargetLibraryInfoRef:
        alias of `~.LLVMOpaqueTargetLibraryInfotData`

"""

import cython
import ctypes
import enum

from rocm.llvm.c.types import LLVMMemoryBufferRef
from rocm.llvm.c.types import LLVMContextRef
from rocm.llvm.c.types import LLVMModuleRef
from rocm.llvm.c.types import LLVMTypeRef
from rocm.llvm.c.types import LLVMValueRef
from rocm.llvm.c.types import LLVMBasicBlockRef
from rocm.llvm.c.types import LLVMMetadataRef
from rocm.llvm.c.types import LLVMNamedMDNodeRef
from rocm.llvm.c.types import LLVMValueMetadataEntry
from rocm.llvm.c.types import LLVMBuilderRef
from rocm.llvm.c.types import LLVMDIBuilderRef
from rocm.llvm.c.types import LLVMModuleProviderRef
from rocm.llvm.c.types import LLVMPassManagerRef
from rocm.llvm.c.types import LLVMPassRegistryRef
from rocm.llvm.c.types import LLVMUseRef
from rocm.llvm.c.types import LLVMAttributeRef
from rocm.llvm.c.types import LLVMDiagnosticInfoRef
from rocm.llvm.c.types import LLVMComdatRef
from rocm.llvm.c.types import LLVMModuleFlagEntry
from rocm.llvm.c.types import LLVMJITEventListenerRef
from rocm.llvm.c.types import LLVMBinaryRef


from rocm.llvm.config.llvm_config import LLVM_DEFAULT_TARGET_TRIPLE
from rocm.llvm.config.llvm_config import LLVM_ENABLE_THREADS
from rocm.llvm.config.llvm_config import LLVM_HAS_ATOMICS
from rocm.llvm.config.llvm_config import LLVM_HOST_TRIPLE
from rocm.llvm.config.llvm_config import LLVM_ON_UNIX
from rocm.llvm.config.llvm_config import LLVM_USE_INTEL_JITEVENTS
from rocm.llvm.config.llvm_config import LLVM_USE_OPROFILE
from rocm.llvm.config.llvm_config import LLVM_USE_PERF
from rocm.llvm.config.llvm_config import LLVM_VERSION_MAJOR
from rocm.llvm.config.llvm_config import LLVM_VERSION_MINOR
from rocm.llvm.config.llvm_config import LLVM_VERSION_PATCH
from rocm.llvm.config.llvm_config import LLVM_VERSION_STRING
from rocm.llvm.config.llvm_config import LLVM_FORCE_ENABLE_STATS
from rocm.llvm.config.llvm_config import LLVM_ENABLE_ZLIB
from rocm.llvm.config.llvm_config import LLVM_ENABLE_ZSTD
from rocm.llvm.config.llvm_config import HAVE_SYSEXITS_H
from rocm.llvm.config.llvm_config import LLVM_UNREACHABLE_OPTIMIZE
from rocm.llvm.config.llvm_config import LLVM_ENABLE_DIA_SDK
from rocm.llvm.config.llvm_config import LLVM_ENABLE_PLUGINS

class _LLVMByteOrdering__Base(enum.IntEnum):
    """Empty enum base class that allows subclassing.
    """
    pass
class LLVMByteOrdering(_LLVMByteOrdering__Base):
    """@{

    Attributes:
        LLVMBigEndian:
            (undocumented)
        LLVMLittleEndian:
            (undocumented)
    """
    LLVMBigEndian = ctarget.LLVMBigEndian
    LLVMLittleEndian = ctarget.LLVMLittleEndian
    @staticmethod
    def ctypes_type():
        """The type of the enum constants as ctypes type."""
        return ctypes.c_uint 


cdef class LLVMOpaqueTargetData:
    """Python wrapper for C type ctarget.LLVMOpaqueTargetData.
    
    Python wrapper for C type ctarget.LLVMOpaqueTargetData.

    If this type is initialized via its `__init__` method, it allocates a member of the underlying C type and
    destroys it again if the wrapper type is deallocted.

    This type also serves as adapter when appearing as argument type in a function signature.
    In this case, the type can further be initialized from the following Python objects
    that you can pass as argument instead:
    
    * `None`:

      This will set the ``self._ptr`` attribute to ``NULL``.

    * `int`:
      
      Interprets the integer value as pointer address and writes it to ``self._ptr``.
      
    * `ctypes.c_void_p`:
      
      Takes the pointer address ``pyobj.value`` and writes it to ``self._ptr``.

    
    Type checks are performed in the above order.

    C Attributes:
        _ptr (C type ``void *``, protected):
            Stores a pointer to the data of the original Python object.
        _ptr_owner (C type ``bint``, protected):
            If this wrapper is the owner of the underlying data.
        _py_buffer (C type ``Py_buffer`, protected):
            Stores a pointer to the data of the original Python object.
        _py_buffer_acquired (C type ``bint``, protected):
            Stores a pointer to the data of the original Python object.
    """
    # members declared in pxd file

    def __cinit__(self):
        self._ptr = NULL
        self.ptr_owner = False
        self._py_buffer_acquired = False

    @staticmethod
    cdef LLVMOpaqueTargetData from_ptr(ctarget.LLVMOpaqueTargetData* ptr, bint owner=False):
        """Factory function to create ``LLVMOpaqueTargetData`` objects from
        given ``ctarget.LLVMOpaqueTargetData`` pointer.
        """
        # Fast call to __new__() that bypasses the __init__() constructor.
        cdef LLVMOpaqueTargetData wrapper = LLVMOpaqueTargetData.__new__(LLVMOpaqueTargetData)
        wrapper._ptr = ptr
        wrapper.ptr_owner = owner
        return wrapper

    @staticmethod
    cdef LLVMOpaqueTargetData from_pyobj(object pyobj):
        """Derives a LLVMOpaqueTargetData from a Python object.

        Derives a LLVMOpaqueTargetData from the given Python object ``pyobj``.
        In case ``pyobj`` is itself an ``LLVMOpaqueTargetData`` reference, this method
        returns it directly. No new ``LLVMOpaqueTargetData`` is created in this case.

        Args:
            pyobj (object): Must be either `None`, a simple, contiguous buffer according to the buffer protocol,
                            or of type `LLVMOpaqueTargetData`, `int`, or `ctypes.c_void_p`

        Note:
            This routine does not perform a copy but returns the original ``pyobj``
            if ``pyobj`` is an instance of LLVMOpaqueTargetData!
        """
        cdef LLVMOpaqueTargetData wrapper = LLVMOpaqueTargetData.__new__(LLVMOpaqueTargetData)
        cdef dict cuda_array_interface = getattr(pyobj, "__cuda_array_interface__", None)

        if pyobj is None:
            wrapper._ptr = NULL
        elif isinstance(pyobj,LLVMOpaqueTargetData):
            return pyobj
        elif isinstance(pyobj,int):
            wrapper._ptr = <ctarget.LLVMOpaqueTargetData*>cpython.long.PyLong_AsVoidPtr(pyobj)
        elif isinstance(pyobj,ctypes.c_void_p):
            wrapper._ptr = <ctarget.LLVMOpaqueTargetData*>cpython.long.PyLong_AsVoidPtr(pyobj.value) if pyobj.value != None else NULL
        elif cpython.buffer.PyObject_CheckBuffer(pyobj):
            err = cpython.buffer.PyObject_GetBuffer( 
                pyobj,
                &wrapper._py_buffer, 
                cpython.buffer.PyBUF_SIMPLE | cpython.buffer.PyBUF_ANY_CONTIGUOUS
            )
            if err == -1:
                raise RuntimeError("failed to create simple, contiguous Py_buffer from Python object")
            wrapper._py_buffer_acquired = True
            wrapper._ptr = <ctarget.LLVMOpaqueTargetData*>wrapper._py_buffer.buf
        else:
            raise TypeError(f"unsupported input type: '{str(type(pyobj))}'")
        return wrapper
    def __dealloc__(self):
        # Release the buffer handle
        if self._py_buffer_acquired is True:
            cpython.buffer.PyBuffer_Release(&self._py_buffer)
    
    def __int__(self):
        """Returns the data's address as long integer.
        """
        return cpython.long.PyLong_FromVoidPtr(self._ptr)
    def __repr__(self):
        return f"<LLVMOpaqueTargetData object, self.ptr={int(self)}>"
    def as_c_void_p(self):
        """Returns the data's address as `ctypes.c_void_p`
        Note:
            Implements as function to not collide with 
            autogenerated property names.
        """
        return ctypes.c_void_p(int(self))
    @staticmethod
    def PROPERTIES():
        return []

    def __contains__(self,item):
        properties = self.PROPERTIES()
        return item in properties

    def __getitem__(self,item):
        properties = self.PROPERTIES()
        if isinstance(item,int):
            if item < 0 or item >= len(properties):
                raise IndexError()
            return getattr(self,properties[item])
        raise ValueError("'item' type must be 'int'")


LLVMTargetDataRef = LLVMOpaqueTargetData

cdef class LLVMOpaqueTargetLibraryInfotData:
    """Python wrapper for C type ctarget.LLVMOpaqueTargetLibraryInfotData.
    
    Python wrapper for C type ctarget.LLVMOpaqueTargetLibraryInfotData.

    If this type is initialized via its `__init__` method, it allocates a member of the underlying C type and
    destroys it again if the wrapper type is deallocted.

    This type also serves as adapter when appearing as argument type in a function signature.
    In this case, the type can further be initialized from the following Python objects
    that you can pass as argument instead:
    
    * `None`:

      This will set the ``self._ptr`` attribute to ``NULL``.

    * `int`:
      
      Interprets the integer value as pointer address and writes it to ``self._ptr``.
      
    * `ctypes.c_void_p`:
      
      Takes the pointer address ``pyobj.value`` and writes it to ``self._ptr``.

    
    Type checks are performed in the above order.

    C Attributes:
        _ptr (C type ``void *``, protected):
            Stores a pointer to the data of the original Python object.
        _ptr_owner (C type ``bint``, protected):
            If this wrapper is the owner of the underlying data.
        _py_buffer (C type ``Py_buffer`, protected):
            Stores a pointer to the data of the original Python object.
        _py_buffer_acquired (C type ``bint``, protected):
            Stores a pointer to the data of the original Python object.
    """
    # members declared in pxd file

    def __cinit__(self):
        self._ptr = NULL
        self.ptr_owner = False
        self._py_buffer_acquired = False

    @staticmethod
    cdef LLVMOpaqueTargetLibraryInfotData from_ptr(ctarget.LLVMOpaqueTargetLibraryInfotData* ptr, bint owner=False):
        """Factory function to create ``LLVMOpaqueTargetLibraryInfotData`` objects from
        given ``ctarget.LLVMOpaqueTargetLibraryInfotData`` pointer.
        """
        # Fast call to __new__() that bypasses the __init__() constructor.
        cdef LLVMOpaqueTargetLibraryInfotData wrapper = LLVMOpaqueTargetLibraryInfotData.__new__(LLVMOpaqueTargetLibraryInfotData)
        wrapper._ptr = ptr
        wrapper.ptr_owner = owner
        return wrapper

    @staticmethod
    cdef LLVMOpaqueTargetLibraryInfotData from_pyobj(object pyobj):
        """Derives a LLVMOpaqueTargetLibraryInfotData from a Python object.

        Derives a LLVMOpaqueTargetLibraryInfotData from the given Python object ``pyobj``.
        In case ``pyobj`` is itself an ``LLVMOpaqueTargetLibraryInfotData`` reference, this method
        returns it directly. No new ``LLVMOpaqueTargetLibraryInfotData`` is created in this case.

        Args:
            pyobj (object): Must be either `None`, a simple, contiguous buffer according to the buffer protocol,
                            or of type `LLVMOpaqueTargetLibraryInfotData`, `int`, or `ctypes.c_void_p`

        Note:
            This routine does not perform a copy but returns the original ``pyobj``
            if ``pyobj`` is an instance of LLVMOpaqueTargetLibraryInfotData!
        """
        cdef LLVMOpaqueTargetLibraryInfotData wrapper = LLVMOpaqueTargetLibraryInfotData.__new__(LLVMOpaqueTargetLibraryInfotData)
        cdef dict cuda_array_interface = getattr(pyobj, "__cuda_array_interface__", None)

        if pyobj is None:
            wrapper._ptr = NULL
        elif isinstance(pyobj,LLVMOpaqueTargetLibraryInfotData):
            return pyobj
        elif isinstance(pyobj,int):
            wrapper._ptr = <ctarget.LLVMOpaqueTargetLibraryInfotData*>cpython.long.PyLong_AsVoidPtr(pyobj)
        elif isinstance(pyobj,ctypes.c_void_p):
            wrapper._ptr = <ctarget.LLVMOpaqueTargetLibraryInfotData*>cpython.long.PyLong_AsVoidPtr(pyobj.value) if pyobj.value != None else NULL
        elif cpython.buffer.PyObject_CheckBuffer(pyobj):
            err = cpython.buffer.PyObject_GetBuffer( 
                pyobj,
                &wrapper._py_buffer, 
                cpython.buffer.PyBUF_SIMPLE | cpython.buffer.PyBUF_ANY_CONTIGUOUS
            )
            if err == -1:
                raise RuntimeError("failed to create simple, contiguous Py_buffer from Python object")
            wrapper._py_buffer_acquired = True
            wrapper._ptr = <ctarget.LLVMOpaqueTargetLibraryInfotData*>wrapper._py_buffer.buf
        else:
            raise TypeError(f"unsupported input type: '{str(type(pyobj))}'")
        return wrapper
    def __dealloc__(self):
        # Release the buffer handle
        if self._py_buffer_acquired is True:
            cpython.buffer.PyBuffer_Release(&self._py_buffer)
    
    def __int__(self):
        """Returns the data's address as long integer.
        """
        return cpython.long.PyLong_FromVoidPtr(self._ptr)
    def __repr__(self):
        return f"<LLVMOpaqueTargetLibraryInfotData object, self.ptr={int(self)}>"
    def as_c_void_p(self):
        """Returns the data's address as `ctypes.c_void_p`
        Note:
            Implements as function to not collide with 
            autogenerated property names.
        """
        return ctypes.c_void_p(int(self))
    @staticmethod
    def PROPERTIES():
        return []

    def __contains__(self,item):
        properties = self.PROPERTIES()
        return item in properties

    def __getitem__(self,item):
        properties = self.PROPERTIES()
        if isinstance(item,int):
            if item < 0 or item >= len(properties):
                raise IndexError()
            return getattr(self,properties[item])
        raise ValueError("'item' type must be 'int'")


LLVMTargetLibraryInfoRef = LLVMOpaqueTargetLibraryInfotData

@cython.embedsignature(True)
def LLVMInitializeAllTargetInfos():
    r"""(No short description, might be part of a group.)

    LLVMInitializeAllTargetInfos - The main program should call this function if
    it wants access to all available targets that LLVM is configured to
    support.
    """
    ctarget.LLVMInitializeAllTargetInfos()    # fully specified


@cython.embedsignature(True)
def LLVMInitializeAllTargets():
    r"""(No short description, might be part of a group.)

    LLVMInitializeAllTargets - The main program should call this function if it
    wants to link in all available targets that LLVM is configured to
    support.
    """
    ctarget.LLVMInitializeAllTargets()    # fully specified


@cython.embedsignature(True)
def LLVMInitializeAllTargetMCs():
    r"""(No short description, might be part of a group.)

    LLVMInitializeAllTargetMCs - The main program should call this function if
    it wants access to all available target MC that LLVM is configured to
    support.
    """
    ctarget.LLVMInitializeAllTargetMCs()    # fully specified


@cython.embedsignature(True)
def LLVMInitializeAllAsmPrinters():
    r"""(No short description, might be part of a group.)

    LLVMInitializeAllAsmPrinters - The main program should call this function if
    it wants all asm printers that LLVM is configured to support, to make them
    available via the TargetRegistry.
    """
    ctarget.LLVMInitializeAllAsmPrinters()    # fully specified


@cython.embedsignature(True)
def LLVMInitializeAllAsmParsers():
    r"""(No short description, might be part of a group.)

    LLVMInitializeAllAsmParsers - The main program should call this function if
    it wants all asm parsers that LLVM is configured to support, to make them
    available via the TargetRegistry.
    """
    ctarget.LLVMInitializeAllAsmParsers()    # fully specified


@cython.embedsignature(True)
def LLVMInitializeAllDisassemblers():
    r"""(No short description, might be part of a group.)

    LLVMInitializeAllDisassemblers - The main program should call this function
    if it wants all disassemblers that LLVM is configured to support, to make
    them available via the TargetRegistry.
    """
    ctarget.LLVMInitializeAllDisassemblers()    # fully specified


@cython.embedsignature(True)
def LLVMInitializeNativeTarget():
    r"""(No short description, might be part of a group.)

    LLVMInitializeNativeTarget - The main program should call this function to
    initialize the native target corresponding to the host.  This is useful
    for JIT applications to ensure that the target gets linked in correctly.

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef int _LLVMInitializeNativeTarget__retval = ctarget.LLVMInitializeNativeTarget()    # fully specified
    return (_LLVMInitializeNativeTarget__retval,)


@cython.embedsignature(True)
def LLVMInitializeNativeAsmParser():
    r"""(No short description, might be part of a group.)

    LLVMInitializeNativeTargetAsmParser - The main program should call this
    function to initialize the parser for the native target corresponding to the
    host.

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef int _LLVMInitializeNativeAsmParser__retval = ctarget.LLVMInitializeNativeAsmParser()    # fully specified
    return (_LLVMInitializeNativeAsmParser__retval,)


@cython.embedsignature(True)
def LLVMInitializeNativeAsmPrinter():
    r"""(No short description, might be part of a group.)

    LLVMInitializeNativeTargetAsmPrinter - The main program should call this
    function to initialize the printer for the native target corresponding to
    the host.

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef int _LLVMInitializeNativeAsmPrinter__retval = ctarget.LLVMInitializeNativeAsmPrinter()    # fully specified
    return (_LLVMInitializeNativeAsmPrinter__retval,)


@cython.embedsignature(True)
def LLVMInitializeNativeDisassembler():
    r"""(No short description, might be part of a group.)

    LLVMInitializeNativeTargetDisassembler - The main program should call this
    function to initialize the disassembler for the native target corresponding
    to the host.

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef int _LLVMInitializeNativeDisassembler__retval = ctarget.LLVMInitializeNativeDisassembler()    # fully specified
    return (_LLVMInitializeNativeDisassembler__retval,)


@cython.embedsignature(True)
def LLVMGetModuleDataLayout(object M):
    r"""(No short description, might be part of a group.)

    Obtain the data layout for a module.

    See:
        `~.Module``~.`~.getDataLayout``()

    Args:
        M (`~.LLVMOpaqueModule`/`~.object`):
            (undocumented)
    """
    _LLVMGetModuleDataLayout__retval = LLVMOpaqueTargetData.from_ptr(ctarget.LLVMGetModuleDataLayout(
        LLVMOpaqueModule.from_pyobj(M)._ptr))    # fully specified
    return (_LLVMGetModuleDataLayout__retval,)


@cython.embedsignature(True)
def LLVMSetModuleDataLayout(object M, object DL):
    r"""(No short description, might be part of a group.)

    Set the data layout for a module.

    See:
        `~.Module``~.`~.setDataLayout``()

    Args:
        M (`~.LLVMOpaqueModule`/`~.object`):
            (undocumented)

        DL (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)
    """
    ctarget.LLVMSetModuleDataLayout(
        LLVMOpaqueModule.from_pyobj(M)._ptr,
        LLVMOpaqueTargetData.from_pyobj(DL)._ptr)    # fully specified


@cython.embedsignature(True)
def LLVMCreateTargetData(const char * StringRep):
    r"""(No short description, might be part of a group.)

    Creates target data from a target layout string.
    See the constructor llvm`~.DataLayout.DataLayout`.

    Args:
        StringRep (`~.bytes`):
            (undocumented)
    """
    _LLVMCreateTargetData__retval = LLVMOpaqueTargetData.from_ptr(ctarget.LLVMCreateTargetData(StringRep))    # fully specified
    return (_LLVMCreateTargetData__retval,)


@cython.embedsignature(True)
def LLVMDisposeTargetData(object TD):
    r"""(No short description, might be part of a group.)

    Deallocates a TargetData.
    See the destructor llvm`~.DataLayout.`~DataLayout.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)
    """
    ctarget.LLVMDisposeTargetData(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr)    # fully specified


@cython.embedsignature(True)
def LLVMAddTargetLibraryInfo(object TLI, object PM):
    r"""(No short description, might be part of a group.)

    Adds target library information to a pass manager. This does not take
    ownership of the target library info.
    See the method llvm`~.PassManagerBase.add`.

    Args:
        TLI (`~.LLVMOpaqueTargetLibraryInfotData`/`~.object`):
            (undocumented)

        PM (`~.LLVMOpaquePassManager`/`~.object`):
            (undocumented)
    """
    ctarget.LLVMAddTargetLibraryInfo(
        LLVMOpaqueTargetLibraryInfotData.from_pyobj(TLI)._ptr,
        LLVMOpaquePassManager.from_pyobj(PM)._ptr)    # fully specified


@cython.embedsignature(True)
def LLVMCopyStringRepOfTargetData(object TD):
    r"""(No short description, might be part of a group.)

    Converts target data to a target layout string. The string must be disposed
    with LLVMDisposeMessage.
    See the constructor llvm`~.DataLayout.DataLayout`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.bytes`
    """
    cdef char * _LLVMCopyStringRepOfTargetData__retval = ctarget.LLVMCopyStringRepOfTargetData(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr)    # fully specified
    return (_LLVMCopyStringRepOfTargetData__retval,)


@cython.embedsignature(True)
def LLVMByteOrder(object TD):
    r"""(No short description, might be part of a group.)

    Returns the byte order of a target, either LLVMBigEndian or
    LLVMLittleEndian.
    See the method llvm`~.DataLayout.isLittleEndian`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.LLVMByteOrdering`
    """
    _LLVMByteOrder__retval = LLVMByteOrdering(ctarget.LLVMByteOrder(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr))    # fully specified
    return (_LLVMByteOrder__retval,)


@cython.embedsignature(True)
def LLVMPointerSize(object TD):
    r"""(No short description, might be part of a group.)

    Returns the pointer size in bytes for a target.
    See the method llvm`~.DataLayout.getPointerSize`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef unsigned int _LLVMPointerSize__retval = ctarget.LLVMPointerSize(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr)    # fully specified
    return (_LLVMPointerSize__retval,)


@cython.embedsignature(True)
def LLVMPointerSizeForAS(object TD, unsigned int AS):
    r"""(No short description, might be part of a group.)

    Returns the pointer size in bytes for a target for a specified
    address space.
    See the method llvm`~.DataLayout.getPointerSize`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

        AS (`~.int`):
            (undocumented)

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef unsigned int _LLVMPointerSizeForAS__retval = ctarget.LLVMPointerSizeForAS(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr,AS)    # fully specified
    return (_LLVMPointerSizeForAS__retval,)


@cython.embedsignature(True)
def LLVMIntPtrType(object TD):
    r"""(No short description, might be part of a group.)

    Returns the integer type that is the same size as a pointer on a target.
    See the method llvm`~.DataLayout.getIntPtrType`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)
    """
    _LLVMIntPtrType__retval = LLVMOpaqueType.from_ptr(ctarget.LLVMIntPtrType(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr))    # fully specified
    return (_LLVMIntPtrType__retval,)


@cython.embedsignature(True)
def LLVMIntPtrTypeForAS(object TD, unsigned int AS):
    r"""(No short description, might be part of a group.)

    Returns the integer type that is the same size as a pointer on a target.
    This version allows the address space to be specified.
    See the method llvm`~.DataLayout.getIntPtrType`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

        AS (`~.int`):
            (undocumented)
    """
    _LLVMIntPtrTypeForAS__retval = LLVMOpaqueType.from_ptr(ctarget.LLVMIntPtrTypeForAS(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr,AS))    # fully specified
    return (_LLVMIntPtrTypeForAS__retval,)


@cython.embedsignature(True)
def LLVMIntPtrTypeInContext(object C, object TD):
    r"""(No short description, might be part of a group.)

    Returns the integer type that is the same size as a pointer on a target.
    See the method llvm`~.DataLayout.getIntPtrType`.

    Args:
        C (`~.LLVMOpaqueContext`/`~.object`):
            (undocumented)

        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)
    """
    _LLVMIntPtrTypeInContext__retval = LLVMOpaqueType.from_ptr(ctarget.LLVMIntPtrTypeInContext(
        LLVMOpaqueContext.from_pyobj(C)._ptr,
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr))    # fully specified
    return (_LLVMIntPtrTypeInContext__retval,)


@cython.embedsignature(True)
def LLVMIntPtrTypeForASInContext(object C, object TD, unsigned int AS):
    r"""(No short description, might be part of a group.)

    Returns the integer type that is the same size as a pointer on a target.
    This version allows the address space to be specified.
    See the method llvm`~.DataLayout.getIntPtrType`.

    Args:
        C (`~.LLVMOpaqueContext`/`~.object`):
            (undocumented)

        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

        AS (`~.int`):
            (undocumented)
    """
    _LLVMIntPtrTypeForASInContext__retval = LLVMOpaqueType.from_ptr(ctarget.LLVMIntPtrTypeForASInContext(
        LLVMOpaqueContext.from_pyobj(C)._ptr,
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr,AS))    # fully specified
    return (_LLVMIntPtrTypeForASInContext__retval,)


@cython.embedsignature(True)
def LLVMSizeOfTypeInBits(object TD, object Ty):
    r"""(No short description, might be part of a group.)

    Computes the size of a type in bytes for a target.
    See the method llvm`~.DataLayout.getTypeSizeInBits`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

        Ty (`~.LLVMOpaqueType`/`~.object`):
            (undocumented)

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef unsigned long long _LLVMSizeOfTypeInBits__retval = ctarget.LLVMSizeOfTypeInBits(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr,
        LLVMOpaqueType.from_pyobj(Ty)._ptr)    # fully specified
    return (_LLVMSizeOfTypeInBits__retval,)


@cython.embedsignature(True)
def LLVMStoreSizeOfType(object TD, object Ty):
    r"""(No short description, might be part of a group.)

    Computes the storage size of a type in bytes for a target.
    See the method llvm`~.DataLayout.getTypeStoreSize`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

        Ty (`~.LLVMOpaqueType`/`~.object`):
            (undocumented)

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef unsigned long long _LLVMStoreSizeOfType__retval = ctarget.LLVMStoreSizeOfType(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr,
        LLVMOpaqueType.from_pyobj(Ty)._ptr)    # fully specified
    return (_LLVMStoreSizeOfType__retval,)


@cython.embedsignature(True)
def LLVMABISizeOfType(object TD, object Ty):
    r"""(No short description, might be part of a group.)

    Computes the ABI size of a type in bytes for a target.
    See the method llvm`~.DataLayout.getTypeAllocSize`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

        Ty (`~.LLVMOpaqueType`/`~.object`):
            (undocumented)

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef unsigned long long _LLVMABISizeOfType__retval = ctarget.LLVMABISizeOfType(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr,
        LLVMOpaqueType.from_pyobj(Ty)._ptr)    # fully specified
    return (_LLVMABISizeOfType__retval,)


@cython.embedsignature(True)
def LLVMABIAlignmentOfType(object TD, object Ty):
    r"""(No short description, might be part of a group.)

    Computes the ABI alignment of a type in bytes for a target.
    See the method llvm`~.DataLayout.getTypeABISize`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

        Ty (`~.LLVMOpaqueType`/`~.object`):
            (undocumented)

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef unsigned int _LLVMABIAlignmentOfType__retval = ctarget.LLVMABIAlignmentOfType(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr,
        LLVMOpaqueType.from_pyobj(Ty)._ptr)    # fully specified
    return (_LLVMABIAlignmentOfType__retval,)


@cython.embedsignature(True)
def LLVMCallFrameAlignmentOfType(object TD, object Ty):
    r"""(No short description, might be part of a group.)

    Computes the call frame alignment of a type in bytes for a target.
    See the method llvm`~.DataLayout.getTypeABISize`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

        Ty (`~.LLVMOpaqueType`/`~.object`):
            (undocumented)

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef unsigned int _LLVMCallFrameAlignmentOfType__retval = ctarget.LLVMCallFrameAlignmentOfType(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr,
        LLVMOpaqueType.from_pyobj(Ty)._ptr)    # fully specified
    return (_LLVMCallFrameAlignmentOfType__retval,)


@cython.embedsignature(True)
def LLVMPreferredAlignmentOfType(object TD, object Ty):
    r"""(No short description, might be part of a group.)

    Computes the preferred alignment of a type in bytes for a target.
    See the method llvm`~.DataLayout.getTypeABISize`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

        Ty (`~.LLVMOpaqueType`/`~.object`):
            (undocumented)

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef unsigned int _LLVMPreferredAlignmentOfType__retval = ctarget.LLVMPreferredAlignmentOfType(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr,
        LLVMOpaqueType.from_pyobj(Ty)._ptr)    # fully specified
    return (_LLVMPreferredAlignmentOfType__retval,)


@cython.embedsignature(True)
def LLVMPreferredAlignmentOfGlobal(object TD, object GlobalVar):
    r"""(No short description, might be part of a group.)

    Computes the preferred alignment of a global variable in bytes for a target.
    See the method llvm`~.DataLayout.getPreferredAlignment`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

        GlobalVar (`~.LLVMOpaqueValue`/`~.object`):
            (undocumented)

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef unsigned int _LLVMPreferredAlignmentOfGlobal__retval = ctarget.LLVMPreferredAlignmentOfGlobal(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr,
        LLVMOpaqueValue.from_pyobj(GlobalVar)._ptr)    # fully specified
    return (_LLVMPreferredAlignmentOfGlobal__retval,)


@cython.embedsignature(True)
def LLVMElementAtOffset(object TD, object StructTy, unsigned long long Offset):
    r"""(No short description, might be part of a group.)

    Computes the structure element that contains the byte offset for a target.
    See the method llvm`~.StructLayout.getElementContainingOffset`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

        StructTy (`~.LLVMOpaqueType`/`~.object`):
            (undocumented)

        Offset (`~.int`):
            (undocumented)

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef unsigned int _LLVMElementAtOffset__retval = ctarget.LLVMElementAtOffset(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr,
        LLVMOpaqueType.from_pyobj(StructTy)._ptr,Offset)    # fully specified
    return (_LLVMElementAtOffset__retval,)


@cython.embedsignature(True)
def LLVMOffsetOfElement(object TD, object StructTy, unsigned int Element):
    r"""(No short description, might be part of a group.)

    Computes the byte offset of the indexed struct element for a target.
    See the method llvm`~.StructLayout.getElementContainingOffset`.

    Args:
        TD (`~.LLVMOpaqueTargetData`/`~.object`):
            (undocumented)

        StructTy (`~.LLVMOpaqueType`/`~.object`):
            (undocumented)

        Element (`~.int`):
            (undocumented)

    Returns:
        A `~.tuple` of size 1 that contains (in that order):

        * `~.int`
    """
    cdef unsigned long long _LLVMOffsetOfElement__retval = ctarget.LLVMOffsetOfElement(
        LLVMOpaqueTargetData.from_pyobj(TD)._ptr,
        LLVMOpaqueType.from_pyobj(StructTy)._ptr,Element)    # fully specified
    return (_LLVMOffsetOfElement__retval,)

__all__ = [
    "_LLVMByteOrdering__Base",
    "LLVMByteOrdering",
    "LLVMOpaqueTargetData",
    "LLVMTargetDataRef",
    "LLVMOpaqueTargetLibraryInfotData",
    "LLVMTargetLibraryInfoRef",
    "LLVMInitializeAllTargetInfos",
    "LLVMInitializeAllTargets",
    "LLVMInitializeAllTargetMCs",
    "LLVMInitializeAllAsmPrinters",
    "LLVMInitializeAllAsmParsers",
    "LLVMInitializeAllDisassemblers",
    "LLVMInitializeNativeTarget",
    "LLVMInitializeNativeAsmParser",
    "LLVMInitializeNativeAsmPrinter",
    "LLVMInitializeNativeDisassembler",
    "LLVMGetModuleDataLayout",
    "LLVMSetModuleDataLayout",
    "LLVMCreateTargetData",
    "LLVMDisposeTargetData",
    "LLVMAddTargetLibraryInfo",
    "LLVMCopyStringRepOfTargetData",
    "LLVMByteOrder",
    "LLVMPointerSize",
    "LLVMPointerSizeForAS",
    "LLVMIntPtrType",
    "LLVMIntPtrTypeForAS",
    "LLVMIntPtrTypeInContext",
    "LLVMIntPtrTypeForASInContext",
    "LLVMSizeOfTypeInBits",
    "LLVMStoreSizeOfType",
    "LLVMABISizeOfType",
    "LLVMABIAlignmentOfType",
    "LLVMCallFrameAlignmentOfType",
    "LLVMPreferredAlignmentOfType",
    "LLVMPreferredAlignmentOfGlobal",
    "LLVMElementAtOffset",
    "LLVMOffsetOfElement",
]